// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PeeUIClient is the client API for PeeUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeeUIClient interface {
	// ListDcimSpecs returns a list of Data Center Infrastructure Manager(s) that can be started through the UI.
	ListDcimSpecs(ctx context.Context, in *ListDcimSpecsRequest, opts ...grpc.CallOption) (PeeUI_ListDcimSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type peeUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPeeUIClient(cc grpc.ClientConnInterface) PeeUIClient {
	return &peeUIClient{cc}
}

func (c *peeUIClient) ListDcimSpecs(ctx context.Context, in *ListDcimSpecsRequest, opts ...grpc.CallOption) (PeeUI_ListDcimSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PeeUI_ServiceDesc.Streams[0], "/v1.PeeUI/ListDcimSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &peeUIListDcimSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PeeUI_ListDcimSpecsClient interface {
	Recv() (*ListDcimSpecsResponse, error)
	grpc.ClientStream
}

type peeUIListDcimSpecsClient struct {
	grpc.ClientStream
}

func (x *peeUIListDcimSpecsClient) Recv() (*ListDcimSpecsResponse, error) {
	m := new(ListDcimSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peeUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.PeeUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeeUIServer is the server API for PeeUI service.
// All implementations must embed UnimplementedPeeUIServer
// for forward compatibility
type PeeUIServer interface {
	// ListDcimSpecs returns a list of Data Center Infrastructure Manager(s) that can be started through the UI.
	ListDcimSpecs(*ListDcimSpecsRequest, PeeUI_ListDcimSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedPeeUIServer()
}

// UnimplementedPeeUIServer must be embedded to have forward compatible implementations.
type UnimplementedPeeUIServer struct {
}

func (UnimplementedPeeUIServer) ListDcimSpecs(*ListDcimSpecsRequest, PeeUI_ListDcimSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDcimSpecs not implemented")
}
func (UnimplementedPeeUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedPeeUIServer) mustEmbedUnimplementedPeeUIServer() {}

// UnsafePeeUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeeUIServer will
// result in compilation errors.
type UnsafePeeUIServer interface {
	mustEmbedUnimplementedPeeUIServer()
}

func RegisterPeeUIServer(s grpc.ServiceRegistrar, srv PeeUIServer) {
	s.RegisterService(&PeeUI_ServiceDesc, srv)
}

func _PeeUI_ListDcimSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDcimSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeeUIServer).ListDcimSpecs(m, &peeUIListDcimSpecsServer{stream})
}

type PeeUI_ListDcimSpecsServer interface {
	Send(*ListDcimSpecsResponse) error
	grpc.ServerStream
}

type peeUIListDcimSpecsServer struct {
	grpc.ServerStream
}

func (x *peeUIListDcimSpecsServer) Send(m *ListDcimSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PeeUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PeeUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeeUI_ServiceDesc is the grpc.ServiceDesc for PeeUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeeUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PeeUI",
	HandlerType: (*PeeUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _PeeUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDcimSpecs",
			Handler:       _PeeUI_ListDcimSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pee-ui.proto",
}
